cores = ('vermelho', 'azul', 'verde', 'amarelo', 'preto')
indice_verde=cores.index('verde')
print (indice_verde)
print (cores.count('azul'))
cores = list(cores)
cores.append('branco')
cores.append('cinza')
cores = tuple(cores)
print (cores)